### ISSUE TITLE
Host schema - Allow `hostname` to be assigned `null` value

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/data-model#30]
See: https://github.com/JupiterOne/data-model/blob/master/src/schemas/Host.json#L14

**Comment by aiwilliams** [comment]
I think it would be helpful to state why this change is necessary. It looks like it's the only `required` property. Perhaps we should drop the requirement?

**Comment by austinkelleher** [comment]
Apologies, I should have been more clear. The reason is that I wanted to keep `google_cloud_instance` and `aws_instance` both `Host` class. `hostname` is a required property, but `aws_instance` does not even use that property currently, so when we introduce the data model validation into the AWS integration, it will break.

I'm not sure whether we want to remove it from required or not. I think removing it from required is probably the right approach, but do we want to establish the concept of a "pseudo-required" property? Properties that we think should be required, but specifying `null` is your opt-out. May not be appropriate for this specific case, but perhaps for others. It looks like there are other cases in this project where `null` is an acceptable value.

**Comment by aiwilliams** [comment]
I think we should make it not required, and then have a way to review conformance to the data model. Saying it is required I think can be misleading from one point of view - someone thinking of the system as a consistent CMDB 😆
